### PR TITLE
filter punctuation

### PR DESCRIPTION
**Pull request by daya0576**
**In L0 Exercise:**
We have to filter punctuation.  

**Example:** 
"filter, punctuation."  ---->  ["filter,", "punctuation."]  ×
should be ["filter", "punctuation"] √

### CODE REVIEW

**Comment by DBWangWei** [comment]
You are right. We just did a barebone token segmentation using space due to lack of time. In L2, we will be talking about this issue again. 

Simple tokenization by a list of punctuations is not enough, e.g., it will break Hewlett-Packard to two tokens. A better approach is probably using some NLP libraries (e.g., NLTK). We will use it later in the course. 

Thanks for pointing this out. If you have a good solution, you can post and I can merge it to the sample solution later.

**Comment by daya0576** [comment]
Cool! I considered that problem too and simply kept the characters using this regex "0-9a-zA-Z\s-", but it might go wrong in complex cases.

 NLP libraries should be the perfect choice, looking forward to learn more about it in L2.

Thanks for ur reply ^^

**Comment by DBWangWei** [comment]
I've improve the code a bit using nltk. It works fairly robustly overall.

**Comment by daya0576** [comment]
Awesome. 👍

**Pull request closed without merging**
